spring.application.name=ArtPark
server.port=8092

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:iiscdb
spring.datasource.username=user
spring.datasource.password=
spring.h2.console.enabled=true